const TEMPLATE_CACHE_PATHNAME_PREFIX = '/template';
const EXTEND_TEMPLATE_LABEL_PREFIX = 'extend:';
const EXTEND_TEMPLATE_PATHNAME_PREFIX = '/extends';
const MAIN_TEMPLATE_PATHNAME_PREFIX = '/main';
const TEMPLATE_FILE_PREFIX = '__template.';

export {
  TEMPLATE_CACHE_PATHNAME_PREFIX,
  EXTEND_TEMPLATE_LABEL_PREFIX,
  EXTEND_TEMPLATE_PATHNAME_PREFIX,
  MAIN_TEMPLATE_PATHNAME_PREFIX,
  TEMPLATE_FILE_PREFIX,
};
