const TEMPLATE_CACHE_PATHNAME_PREFIX = '/template';
const EXTEND_TEMPLATE_LABEL_PREFIX = 'extend:';
const EXTEND_TEMPLATE_PATHNAME_PREFIX = '/extends';
const MAIN_TEMPLATE_PATHNAME_PREFIX = '/main';
const TEMPLATE_FILE_PREFIX = '__template.';
const TEMPLATE_CONFIG_FILE_NAMES = [
  'dollie.json',
  'dollie.js',
  '.dollie.json',
  '.dollie.js',
];
const EXTEND_TEMPLATE_PREFIX = '$EXTEND';

export {
  TEMPLATE_CACHE_PATHNAME_PREFIX,
  EXTEND_TEMPLATE_LABEL_PREFIX,
  EXTEND_TEMPLATE_PATHNAME_PREFIX,
  MAIN_TEMPLATE_PATHNAME_PREFIX,
  TEMPLATE_FILE_PREFIX,
  TEMPLATE_CONFIG_FILE_NAMES,
  EXTEND_TEMPLATE_PREFIX,
};
